import type { AnnouncementSummary } from "../types/announcements";
import type { ApplicationSettings } from "../types/settings";
import type { CertificateTemplate, IssuedCertificate } from "../types/certificates";
import type { AuditLogEntry } from "../types/audit";
import type { AttendanceSummary } from "../types/attendance";
import type { DailyLogEntry, FinalReport, MonthlyReport, Project } from "../types/internshipReports";
import type { DeviceDetails } from "../types/devices";
import type { InternshipSummary } from "../types/internships";
import type { RfidCardSummary } from "../types/cards";
import type { MemberAttendanceHistoryItem, MemberDetails, MemberInternshipSummary } from "../types/members";
import type { StudentPortalSummary } from "../types/portal";
import type { UserSummary } from "../types/users";

export const mockDatabase = {
  /** Blank/letterhead PDFs a certificate is generated from. Uploaded by an admin. */
  certificateTemplates: [] as CertificateTemplate[],
  issuedCertificates: [] as IssuedCertificate[],
  members: [
    {
      id: "stu-1001",
      photoUrl: null,
      memberNumber: "2023001",
      fullName: "Ana Beatriz Souza",
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      originSchool: "Escola Secundária Augusto Cabrita",
      isExternal: false,
      course: "Information Systems",
      className: "IS-3A",
      academicYear: "2026",
      status: "active",
      assignedCardUid: "04A1C3E9",
      internshipStatus: "in-progress",
      // Volunteer hours earned before/alongside the internship — deliberately a different
      // figure from `internshipCompletedHours` because the two count towards different things.
      teamHours: 64,
      birthDate: "2004-03-12",
      emergencyContact: "Marcos Souza - +55 11 97777-1122",
      notes: "Prefers afternoon attendance reports.",
      orientadorName: "Prof. L. Santos",
      internshipRequiredHours: 240,
      internshipCompletedHours: 128,
      internshipStartDate: "2026-02-10",
      internshipEndDate: "2026-11-30",
    },
    {
      id: "stu-1002",
      photoUrl: null,
      memberNumber: "2023002",
      fullName: "Bruno Henrique Costa",
      email: "bruno.costa@picaponto.edu",
      phone: "+55 11 98888-1002",
      originSchool: "Escola Secundária Augusto Cabrita",
      isExternal: false,
      course: "Computer Engineering",
      className: "CE-2B",
      academicYear: "2026",
      status: "active",
      assignedCardUid: null,
      internshipStatus: "not-assigned",
      teamHours: 92,
      birthDate: "2003-10-21",
      emergencyContact: "Fernanda Costa - +55 11 97777-2233",
      notes: "Volunteer team member. Helps around the club and has projects assigned.",
      orientadorName: null,
      internshipRequiredHours: 0,
      internshipCompletedHours: 0,
      internshipStartDate: null,
      internshipEndDate: null,
    },
    {
      // An FCT intern enrolled at another school: Equipa Técnica hosts them, but the
      // orientador belongs to their own school and the academic fields come from there.
      id: "stu-1003",
      photoUrl: null,
      memberNumber: "2023114",
      fullName: "Carolina Mendes Rocha",
      email: "carolina.rocha@esbarreiro.edu",
      phone: "+351 912 445 118",
      originSchool: "Escola Secundária de Barreiro",
      isExternal: true,
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      academicYear: "2026",
      status: "active",
      assignedCardUid: null,
      internshipStatus: "in-progress",
      teamHours: 18,
      birthDate: "2005-01-08",
      emergencyContact: "Helena Rocha - +351 912 445 002",
      notes: "External FCT intern. Attendance sheet is countersigned by her own school.",
      orientadorName: "Prof.ª C. Marques",
      internshipRequiredHours: 210,
      internshipCompletedHours: 46,
      internshipStartDate: "2026-04-06",
      internshipEndDate: "2026-12-18",
    },
  ] as MemberDetails[],
  cards: [
    {
      id: "card-1",
      uid: "04A1C3E9",
      ownerName: "Ana Beatriz Souza",
      ownerId: "stu-1001",
      status: "assigned",
      lastScanAt: "2026-07-27T08:54:00.000Z",
      assignedAt: "2026-02-01T08:00:00.000Z",
      replacedByUid: null,
    },
    {
      id: "card-2",
      uid: "09F7B1D2",
      ownerName: null,
      ownerId: null,
      status: "available",
      lastScanAt: null,
      assignedAt: null,
      replacedByUid: null,
    },
  ] as RfidCardSummary[],
  attendance: [
    {
      id: "att-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-27",
      entry: "07:58",
      exit: "12:10",
      hours: 4.2,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "System",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-2",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-27",
      entry: null,
      exit: null,
      hours: null,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "missing",
      corrections: 1,
      notes: "Manual correction requested.",
      createdBy: "Admin",
      updatedBy: "Coordinator",
      updatedAt: "2026-07-27T09:15:00.000Z",
    },
  ] as AttendanceSummary[],
  devices: [
    {
      id: "dev-1",
      name: "Terminal A",
      location: "Main Gate",
      firmwareVersion: "1.4.2",
      firmwareChannel: "stable",
      status: "online",
      ipAddress: "192.168.10.21",
      wifiStrength: 89,
      lastHeartbeatAt: "2026-07-27T09:13:00.000Z",
      queueSize: 0,
      description: "Primary entrance attendance terminal.",
      heartbeatIntervalMinutes: 2,
      notes: "",
    },
    {
      id: "dev-2",
      name: "Terminal B",
      location: "Lab 3",
      firmwareVersion: "1.3.9",
      firmwareChannel: "beta",
      status: "warning",
      ipAddress: "192.168.10.34",
      wifiStrength: 56,
      lastHeartbeatAt: "2026-07-27T08:52:00.000Z",
      queueSize: 4,
      description: "Lab terminal with queued sync events.",
      heartbeatIntervalMinutes: 5,
      notes: "Investigate weak WiFi signal.",
    },
  ] as DeviceDetails[],
  // Only members who actually carry out an FCT internship appear here. Everyone else on
  // the roster is a volunteer team member whose hours live on the member record.
  internships: [
    {
      id: "int-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      hostEntity: "Escola Secundária Augusto Cabrita",
      requiredHours: 240,
      completedHours: 128,
      remainingHours: 112,
      orientador: "Prof. L. Santos",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-02-10",
      endDate: "2026-11-30",
      status: "active",
      notes: "Weekly review every Friday.",
      certificateIssuedAt: null,
    },
    {
      id: "int-2",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      hostEntity: "Escola Secundária Augusto Cabrita",
      requiredHours: 210,
      completedHours: 46,
      remainingHours: 164,
      orientador: "Prof.ª C. Marques",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-04-06",
      endDate: "2026-12-18",
      status: "active",
      notes: "Attendance sheet countersigned by Escola Secundária de Barreiro.",
      certificateIssuedAt: null,
    },
  ] as InternshipSummary[],
  announcements: [
    {
      id: "ann-1",
      title: "Report submission window",
      body: "Monthly attendance reports are available until Friday. Generate yours from the Reports page before the deadline.",
      audience: "all",
      priority: "important",
      status: "published",
      publishedAt: "2026-07-27",
      createdAt: "2026-07-26T18:00:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
    {
      id: "ann-2",
      title: "Card replacement reminder",
      body: "Notify the support desk if your RFID card is lost so attendance is not interrupted.",
      audience: "all",
      priority: "normal",
      status: "published",
      publishedAt: "2026-07-24",
      createdAt: "2026-07-24T09:30:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
    {
      id: "ann-3",
      title: "Plano de trabalho individual due",
      body: "Official interns must hand the signed plano de trabalho individual to the professor orientador this week.",
      audience: "official-internship",
      priority: "urgent",
      status: "published",
      publishedAt: "2026-07-22",
      createdAt: "2026-07-22T08:15:00.000Z",
      createdBy: "Paulo Rios",
      updatedAt: null,
    },
    {
      id: "ann-4",
      title: "Surplus hours cut-off",
      body: "Hours registered after 31 July no longer count towards the current certificate period.",
      audience: "equipa-hours",
      priority: "important",
      status: "draft",
      publishedAt: null,
      createdAt: "2026-07-28T11:00:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
  ] as AnnouncementSummary[],
  projects: [
    {
      id: "prj-terminals",
      name: "RFID attendance terminals",
      description: "Build, test and deploy the gate and lab terminals.",
      status: "active",
      owner: "Eng. R. Ferreira",
    },
    {
      id: "prj-network",
      name: "Block B network refresh",
      description: "Switch replacement and structured cabling clean-up.",
      status: "active",
      owner: "Eng. R. Ferreira",
    },
    {
      id: "prj-inventory",
      name: "Lab inventory and documentation",
      description: "Keep the hardware inventory and wiring documentation current.",
      status: "paused",
      owner: "Prof. L. Santos",
    },
  ] as Project[],
  dailyLogs: [
    {
      id: "log-d-1",
      studentId: "stu-1001",
      date: "2026-07-27",
      hours: 4.2,
      projectId: "prj-terminals",
      activities: "Assembled and tested two RFID terminals for the main gate.",
      learnings: "Learned how the RDM6300 reader reports UIDs over UART.",
      difficulties: "Intermittent readings when the antenna was too close to the case.",
      status: "submitted",
      createdAt: "2026-07-27T12:30:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-2",
      studentId: "stu-1001",
      date: "2026-07-26",
      hours: 4.1,
      projectId: "prj-inventory",
      activities: "Documented the attendance terminal wiring and updated the lab inventory.",
      learnings: "Improved technical writing for hardware documentation.",
      difficulties: "",
      status: "submitted",
      createdAt: "2026-07-26T12:20:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-3",
      studentId: "stu-1001",
      date: "2026-06-30",
      hours: 5,
      projectId: "prj-network",
      activities: "Supported the network team during the switch replacement in block B.",
      learnings: "First contact with structured cabling and patch panel labelling.",
      difficulties: "Cable labelling was inconsistent with the existing plan.",
      status: "submitted",
      createdAt: "2026-06-30T17:00:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-4",
      studentId: "stu-1003",
      date: "2026-07-27",
      hours: 4,
      projectId: "prj-terminals",
      activities: "Flashed the new firmware onto three terminals and re-ran the UID read tests.",
      learnings: "Understood how the OTA channel picks up a firmware build.",
      difficulties: "One terminal kept dropping off the network mid-flash.",
      status: "submitted",
      createdAt: "2026-07-27T16:10:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-5",
      studentId: "stu-1003",
      date: "2026-07-24",
      hours: 3.5,
      projectId: "prj-terminals",
      activities: "Wrote the terminal test checklist and ran it against the gate unit.",
      learnings: "Writing a checklist first made the retest much faster.",
      difficulties: "",
      status: "draft",
      createdAt: "2026-07-24T15:40:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-6",
      studentId: "stu-1002",
      date: "2026-06-18",
      hours: 3,
      projectId: "prj-network",
      activities: "Helped label patch panels in block B and updated the cabling plan.",
      learnings: "Learned the school's patch panel naming convention.",
      difficulties: "",
      status: "submitted",
      createdAt: "2026-06-18T16:00:00.000Z",
      updatedAt: null,
    },
  ] as DailyLogEntry[],
  monthlyReports: [
    {
      id: "mr-1",
      studentId: "stu-1001",
      month: "2026-06",
      periodStart: "2026-06-01",
      periodEnd: "2026-06-30",
      totalHours: 5,
      entriesCount: 1,
      activitiesCompleted: ["Supported the network team during the switch replacement in block B."],
      activitiesPlanned: ["Finish the terminal enclosure assembly.", "Start the internship dossier."],
      mainDifficulties: "Cable labelling was inconsistent with the existing plan.",
      status: "submitted",
      generatedAt: "2026-07-01T09:00:00.000Z",
      submittedAt: "2026-07-01T10:15:00.000Z",
    },
  ] as MonthlyReport[],
  finalReports: {
    "stu-1001": {
      studentId: "stu-1001",
      companyCharacterization: "",
      activitiesPerformed: "",
      difficulties: "",
      newLearnings: "",
      occurrences: "",
      other: "",
      status: "draft",
      updatedAt: null,
      submittedAt: null,
    },
  } as Record<string, FinalReport>,
  users: [
    {
      id: "user-1",
      fullName: "Carla Menezes",
      email: "carla.menezes@picaponto.edu",
      role: "administrator",
      status: "active",
      lastLoginAt: "2026-07-27T08:05:00.000Z",
      memberId: null,
    },
    {
      id: "user-2",
      fullName: "Paulo Rios",
      email: "paulo.rios@picaponto.edu",
      role: "coordinator",
      status: "active",
      lastLoginAt: "2026-07-26T19:40:00.000Z",
      memberId: null,
    },
    {
      // Created from a member record, so the roster shows this member as having access.
      id: "user-3",
      fullName: "Ana Beatriz Souza",
      email: "ana.souza@picaponto.edu",
      role: "viewer",
      status: "active",
      lastLoginAt: "2026-07-25T09:12:00.000Z",
      memberId: "stu-1001",
    },
  ] as UserSummary[],
  auditLogs: [
    {
      id: "log-1",
      timestamp: "2026-07-27T09:02:00.000Z",
      userName: "Carla Menezes",
      action: "CREATE",
      entity: "attendance",
      description: "Manual correction created for Bruno Henrique Costa.",
      ipAddress: "192.168.10.12",
      deviceName: "Admin Console",
    },
    {
      id: "log-2",
      timestamp: "2026-07-27T08:59:00.000Z",
      userName: "System",
      action: "UPDATE",
      entity: "device",
      description: "Heartbeat updated for Terminal A.",
      ipAddress: "192.168.10.21",
      deviceName: "Terminal A",
    },
  ] as AuditLogEntry[],
  settings: {
    schoolName: "Pica Ponto Institute",
    logoUrl: "",
    theme: "dark",
    language: "Portuguese (Brazil)",
    timezone: "America/Sao_Paulo",
    attendance: {
      duplicateScanTimeoutMinutes: 15,
      workingDayStart: "07:00",
      workingDayEnd: "18:00",
      entryToleranceMinutes: 10,
      exitToleranceMinutes: 10,
    },
    devices: {
      otaEnabled: true,
      apiUrl: "https://api.picaponto.local",
      backupEnabled: true,
      backupPath: "C:/PicaPonto/backups",
    },
    notifications: {
      emailEnabled: true,
      desktopEnabled: true,
      recipients: "support@picaponto.edu",
      events: ["pending-corrections", "device-offline", "daily-log-gaps"],
      quietHoursEnabled: true,
      quietHoursStart: "19:00",
      quietHoursEnd: "08:00",
    },
    security: {
      confirmNewDevices: true,
      sessionTimeoutMinutes: 60,
      twoFactorEnabled: false,
      trustedDevices: [
        { id: "dev-1", name: "Lab desktop — Windows", lastUsedAt: "2026-07-27T08:02:00.000Z", current: true },
        { id: "dev-2", name: "Coordination laptop — Windows", lastUsedAt: "2026-07-24T17:41:00.000Z", current: false },
      ],
    },
    workHours: {
      schedule: [
        { weekday: "monday", open: true, start: "08:30", end: "17:30" },
        { weekday: "tuesday", open: true, start: "08:30", end: "17:30" },
        { weekday: "wednesday", open: true, start: "08:30", end: "17:30" },
        { weekday: "thursday", open: true, start: "08:30", end: "17:30" },
        { weekday: "friday", open: true, start: "08:30", end: "16:00" },
        { weekday: "saturday", open: false, start: "09:00", end: "13:00" },
        { weekday: "sunday", open: false, start: "09:00", end: "13:00" },
      ],
      expectedWeeklyHours: 20,
      closedDates: ["2026-12-24", "2026-12-25", "2026-12-31"],
    },
    logRetentionDays: 365,
  } as ApplicationSettings,
  portal: {
    profile: {
      fullName: "Ana Beatriz Souza",
      studentNumber: "2023001",
      course: "Information Systems",
      className: "IS-3A",
      photoUrl: null,
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      assignedOrientador: "Prof. L. Santos",
      assignedMonitor: "Eng. R. Ferreira",
    },
    currentInternshipStatus: "In progress",
    completedHours: 128,
    remainingHours: 112,
    attendanceToday: "Present",
    attendanceCalendar: [
      { date: "2026-07-21", status: "present" },
      { date: "2026-07-22", status: "present" },
      { date: "2026-07-23", status: "late" },
      { date: "2026-07-24", status: "present" },
      { date: "2026-07-25", status: "holiday" },
      { date: "2026-07-26", status: "absent" },
      { date: "2026-07-27", status: "present" },
    ],
    recentAttendance: [
      { date: "2026-07-27", entry: "07:58", exit: "12:10", hours: 4.2, status: "Present" },
      { date: "2026-07-26", entry: "07:54", exit: "12:02", hours: 4.1, status: "Present" },
      { date: "2026-07-25", entry: "—", exit: "—", hours: 0, status: "Holiday" },
    ],
    weeklyStatistics: [
      { label: "Mon", value: 6 },
      { label: "Tue", value: 7 },
      { label: "Wed", value: 8 },
      { label: "Thu", value: 7 },
      { label: "Fri", value: 6 },
      { label: "Sat", value: 0 },
      { label: "Sun", value: 0 },
    ],
    monthlyStatistics: [
      { label: "Week 1", value: 34 },
      { label: "Week 2", value: 37 },
      { label: "Week 3", value: 33 },
      { label: "Week 4", value: 40 },
    ],
    internshipProgress: 53,
    achievements: [
      {
        id: "ach-1",
        title: "Perfect week",
        description: "Completed five consecutive days with on-time scans.",
        achievedAt: "2026-07-20",
      },
      {
        id: "ach-2",
        title: "Internship milestone",
        description: "Reached 50% of required internship hours.",
        achievedAt: "2026-07-18",
      },
    ],
    announcements: [
      {
        id: "ann-1",
        title: "Report submission window",
        description: "Monthly attendance reports are available until Friday.",
        publishedAt: "2026-07-27",
      },
      {
        id: "ann-2",
        title: "Card replacement reminder",
        description: "Notify the support desk if your RFID card is lost.",
        publishedAt: "2026-07-24",
      },
    ],
  } as StudentPortalSummary,
  memberHistory: {
    "stu-1001": [
      { id: "hist-1", date: "2026-07-27", entry: "07:58", exit: "12:10", hours: 4.2, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-2", date: "2026-07-26", entry: "07:54", exit: "12:02", hours: 4.1, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-3", date: "2026-07-25", entry: "—", exit: "—", hours: 0, deviceName: "—", status: "missing" },
    ] as MemberAttendanceHistoryItem[],
    "stu-1002": [
      { id: "hist-4", date: "2026-07-27", entry: "—", exit: "—", hours: 0, deviceName: "Terminal B - Lab", status: "missing" },
      { id: "hist-5", date: "2026-07-26", entry: "08:10", exit: "12:17", hours: 4.1, deviceName: "Terminal B - Lab", status: "corrected" },
    ] as MemberAttendanceHistoryItem[],
  } as Record<string, MemberAttendanceHistoryItem[]>,
  memberInternships: {
    "stu-1001": {
      memberId: "stu-1001",
      requiredHours: 240,
      completedHours: 128,
      remainingHours: 112,
      orientador: "Prof. L. Santos",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-02-10",
      endDate: "2026-11-30",
      status: "in-progress",
    } as MemberInternshipSummary,
    "stu-1003": {
      memberId: "stu-1003",
      requiredHours: 210,
      completedHours: 46,
      remainingHours: 164,
      orientador: "Prof.ª C. Marques",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-04-06",
      endDate: "2026-12-18",
      status: "in-progress",
    } as MemberInternshipSummary,
  } as Record<string, MemberInternshipSummary>,
};
