import type { AnnouncementRead, AnnouncementSummary } from "../types/announcements";
import type { ApplicationSettings } from "../types/settings";
import type {
  CertificateRequest,
  CertificateTemplate,
  IssuedCertificate,
  SchoolCertificateProfile,
} from "../types/certificates";
import type { CalendarEvent } from "../types/calendarEvents";
import type { ProfileChangeRequest } from "../types/profileChangeRequests";
import type { AuditLogEntry } from "../types/audit";
import type { AttendanceSummary } from "../types/attendance";
import type { DailyLogEntry, FinalReport, MonthlyReport } from "../types/internshipReports";
import type { Project, ProjectActivityEvent, ProjectTask } from "../types/projects";
import type { TeamMoment } from "../types/moments";
import type { AttendanceCorrectionRequest } from "../types/attendanceCorrections";
import type { DeviceDetails } from "../types/devices";
import type { StoredInternship } from "../types/internships";
import type { RfidCardSummary } from "../types/cards";
import type { MemberAttendanceHistoryItem, StoredMember } from "../types/members";
import type { StoredPortalSummary } from "../types/portal";
import type { ParticipationPeriod } from "../types/participation";
import type { UserSummary } from "../types/users";

export const mockDatabase = {
  /** Blank/letterhead PDFs a certificate is generated from. Uploaded by an admin. */
  certificateTemplates: [] as CertificateTemplate[],
  issuedCertificates: [] as IssuedCertificate[],
  /**
   * FCT certificate profiles, one per school an intern can be enrolled at.
   *
   * Seeded with the host school so the workflow has something to run against
   * before anybody configures a partner school. The template is null: a document
   * has to be uploaded before an FCT certificate can be approved, which is the
   * refusal `issueCertificate` produces rather than generating an unbranded PDF.
   */
  schoolCertificateProfiles: [
    {
      id: "scp-1",
      schoolName: "Escola Secundária Augusto Cabrita",
      template: null,
      signatoryName: "Carla Menezes",
      signatoryRole: "Coordenadora de Cursos Profissionais",
      notes: "Host school. Also used for interns enrolled here.",
      updatedAt: "2026-08-01T09:00:00.000Z",
    },
  ] as SchoolCertificateProfile[],
  /** Members asking for a certificate they are eligible for. Approval generates it. */
  certificateRequests: [] as CertificateRequest[],
  /** Members asking for a controlled identity field to be changed. */
  profileChangeRequests: [
    {
      id: "pcr-1",
      memberId: "stu-1002",
      memberName: "Bruno Carvalho Lima",
      field: "phone",
      currentValue: "+55 11 98888-1002",
      requestedValue: "+351 912 004 118",
      reason: "I changed carrier over the summer and the old number no longer reaches me.",
      status: "pending",
      createdAt: "2026-08-28T10:12:00.000Z",
      resolvedAt: null,
      resolvedBy: null,
      resolutionNote: "",
      appliedToRecord: false,
    },
  ] as ProfileChangeRequest[],
  /**
   * Calendar events.
   *
   * Deliberately spread across the three visibilities so the rules are visible in
   * the fixture: one club-wide event everybody sees, one project event only the
   * people on that project see, and one personal note only its author sees.
   */
  calendarEvents: [
    {
      id: "evt-1",
      title: "Equipa Técnica monthly meeting",
      description: "Progress round-up and workload for the coming month. Lab 3.",
      date: "2026-09-04",
      startTime: "14:30",
      endTime: "16:00",
      category: "meeting",
      visibility: "team",
      projectId: null,
      authorId: "user-1",
      authorName: "Carla Menezes",
      createdAt: "2026-08-20T09:00:00.000Z",
      updatedAt: null,
    },
    {
      id: "evt-2",
      title: "Terminal enclosure assembly session",
      description: "Bring the printed brackets. Continues the work from last week.",
      date: "2026-09-09",
      startTime: "09:00",
      endTime: "12:30",
      category: "session",
      visibility: "project",
      projectId: "prj-1",
      authorId: "user-2",
      authorName: "Paulo Rios",
      createdAt: "2026-08-24T11:20:00.000Z",
      updatedAt: null,
    },
    {
      id: "evt-3",
      title: "Draft the monthly balance",
      description: "Write up August before the review window closes.",
      date: "2026-09-02",
      startTime: null,
      endTime: null,
      category: "deadline",
      visibility: "personal",
      projectId: null,
      authorId: "stu-1001",
      authorName: "Ana Beatriz Souza",
      createdAt: "2026-08-29T18:40:00.000Z",
      updatedAt: null,
    },
  ] as CalendarEvent[],
  members: [
    {
      id: "stu-1001",
      photoUrl: null,
      memberNumber: "2023001",
      fullName: "Ana Beatriz Souza",
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      originSchool: "Escola Secundária Augusto Cabrita",
      isExternal: false,
      course: "Information Systems",
      className: "IS-3A",
      academicYear: "2026",
      status: "active",
      assignedCardUid: "04A1C3E9",
      internshipStatus: "in-progress",
      birthDate: "2004-03-12",
      emergencyContact: "Marcos Souza - +55 11 97777-1122",
      notes: "Prefers afternoon attendance reports.",
      orientadorName: "Prof. L. Santos",
    },
    {
      id: "stu-1002",
      photoUrl: null,
      memberNumber: "2023002",
      fullName: "Bruno Henrique Costa",
      email: "bruno.costa@picaponto.edu",
      phone: "+55 11 98888-1002",
      originSchool: "Escola Secundária Augusto Cabrita",
      isExternal: false,
      course: "Computer Engineering",
      className: "CE-2B",
      academicYear: "2026",
      status: "active",
      assignedCardUid: null,
      internshipStatus: "not-assigned",
      birthDate: "2003-10-21",
      emergencyContact: "Fernanda Costa - +55 11 97777-2233",
      notes: "Volunteer team member. Helps around the club and has projects assigned.",
      orientadorName: null,
    },
    {
      // An FCT intern enrolled at another school: Equipa Técnica hosts them, but the
      // orientador belongs to their own school and the academic fields come from there.
      id: "stu-1003",
      photoUrl: null,
      memberNumber: "2023114",
      fullName: "Carolina Mendes Rocha",
      email: "carolina.rocha@esbarreiro.edu",
      phone: "+351 912 445 118",
      originSchool: "Escola Secundária de Barreiro",
      isExternal: true,
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      academicYear: "2026",
      status: "active",
      assignedCardUid: null,
      internshipStatus: "in-progress",
      birthDate: "2005-01-08",
      emergencyContact: "Helena Rocha - +351 912 445 002",
      notes: "External FCT intern. Attendance sheet is countersigned by her own school.",
      orientadorName: "Prof.ª C. Marques",
    },
  ] as StoredMember[],
  cards: [
    {
      id: "card-1",
      uid: "04A1C3E9",
      ownerName: "Ana Beatriz Souza",
      ownerId: "stu-1001",
      status: "assigned",
      lastScanAt: "2026-07-27T08:54:00.000Z",
      assignedAt: "2026-02-01T08:00:00.000Z",
      replacedByUid: null,
      registeredAtDeviceId: "dev-1",
      registeredAtDeviceName: "Terminal A — Main Gate",
      registeredAt: "2026-02-01T07:55:00.000Z",
    },
    {
      id: "card-2",
      uid: "09F7B1D2",
      ownerName: null,
      ownerId: null,
      status: "available",
      lastScanAt: null,
      assignedAt: null,
      replacedByUid: null,
      registeredAtDeviceId: "dev-2",
      registeredAtDeviceName: "Terminal B — Lab 3",
      registeredAt: "2026-03-14T10:02:00.000Z",
    },
  ] as RfidCardSummary[],
  /*
   * Three months of attendance for the three seeded members.
   *
   * Each member keeps a fixed weekly rota rather than a random scatter, so the
   * date-range filter, month grouping and per-member totals all have something
   * coherent to work on. The anomalies are deliberate and few — four late
   * arrivals, four no-shows, one corrected day and one missing exit scan — which
   * is what keeps them findable instead of lost in noise.
   *
   * Four of these days are referenced by `attendanceCorrectionRequests` below;
   * changing their ids or dates breaks that link.
   */
  attendance: [
    {
      id: "att-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-01",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-2",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-01",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-3",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-02",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-4",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-02",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-5",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-03",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-6",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-04",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-7",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-04",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-8",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-05",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-9",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-08",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-10",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-08",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-11",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-09",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-12",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-09",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-13",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-10",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-14",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-11",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-15",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-11",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-16",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-12",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-17",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-15",
      entry: null,
      exit: null,
      hours: null,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "missing",
      corrections: 0,
      notes: "No scan recorded for this day.",
      createdBy: "System",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-18",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-15",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-19",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-16",
      entry: "15:00",
      exit: "17:30",
      hours: 2.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "late",
      corrections: 0,
      notes: "Arrived after the tolerance window.",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-20",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-16",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-21",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-17",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-22",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-18",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-23",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-18",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-24",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-19",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-25",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-22",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-26",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-22",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-27",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-23",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-28",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-23",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-29",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-24",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-30",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-25",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-31",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-25",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-32",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-26",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-33",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-06-29",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-34",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-29",
      entry: null,
      exit: null,
      hours: null,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "missing",
      corrections: 0,
      notes: "No scan recorded for this day.",
      createdBy: "System",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-35",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-06-30",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-36",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-06-30",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-37",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-01",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-38",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-02",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-39",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-02",
      entry: null,
      exit: null,
      hours: null,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "missing",
      corrections: 0,
      notes: "No scan recorded for this day.",
      createdBy: "System",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-40",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-03",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-41",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-06",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-42",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-06",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-43",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-07",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-44",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-07",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-45",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-08",
      entry: "09:05",
      exit: "12:10",
      hours: 3.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "late",
      corrections: 0,
      notes: "Arrived after the tolerance window.",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-46",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-09",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-47",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-09",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-48",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-10",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-49",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-13",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-50",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-13",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-51",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-14",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-52",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-14",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-53",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-15",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-54",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-16",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-55",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-16",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-56",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-17",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-57",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-20",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-58",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-20",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-59",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-21",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-60",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-21",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-61",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-22",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-62",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-23",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-63",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-23",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-64",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-24",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-65",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-27",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-66",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-27",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-67",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-28",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-68",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-28",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-69",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-29",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-70",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-30",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-71",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-30",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-72",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-07-31",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-73",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-03",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-74",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-03",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-75",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-04",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-76",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-04",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-77",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-05",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-78",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-06",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-79",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-06",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-80",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-07",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-81",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-10",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-82",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-10",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-83",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-11",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-84",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-11",
      entry: "09:00",
      exit: "12:05",
      hours: 3.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "late",
      corrections: 0,
      notes: "Arrived after the tolerance window.",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-85",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-12",
      entry: "08:05",
      exit: "12:10",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-86",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-13",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-87",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-13",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-88",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-14",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-89",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-17",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-90",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-17",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-91",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-18",
      entry: "14:00",
      exit: "17:50",
      hours: 3.83,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "corrected",
      corrections: 1,
      notes: "Exit time corrected after the terminal missed the scan.",
      createdBy: "Terminal",
      updatedBy: "System Administrator",
      updatedAt: "2026-08-18T18:40:00.000Z",
    },
    {
      id: "att-92",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-18",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-93",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-19",
      entry: "09:05",
      exit: "12:10",
      hours: 3.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "late",
      corrections: 0,
      notes: "Arrived after the tolerance window.",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-94",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-20",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-95",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-20",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-96",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-21",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-97",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-24",
      entry: "08:00",
      exit: "12:15",
      hours: 4.25,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-98",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-24",
      entry: "13:30",
      exit: "17:40",
      hours: 4.17,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-99",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-25",
      entry: "14:00",
      exit: "17:30",
      hours: 3.5,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-100",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-25",
      entry: "08:00",
      exit: "12:05",
      hours: 4.08,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-101",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-26",
      entry: "08:05",
      exit: null,
      hours: null,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "missing",
      corrections: 0,
      notes: "Entry scan only — no exit scan recorded.",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-102",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-08-27",
      entry: "13:30",
      exit: "17:35",
      hours: 4.08,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-103",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-08-27",
      entry: "14:05",
      exit: "17:25",
      hours: 3.33,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-104",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      course: "Técnico de Gestão e Programação de Sistemas Informáticos",
      className: "GPSI-3B",
      date: "2026-08-28",
      entry: "08:10",
      exit: "12:00",
      hours: 3.83,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "Terminal",
      updatedBy: null,
      updatedAt: null,
    },
  ] as AttendanceSummary[],

  /*
   * One correction request in each lifecycle state, so every branch of the
   * reviewer's queue and of the member's own view can be exercised without
   * having to create the data by hand first:
   *
   *   acr-1  pending    Ana, missing exit scan, still waiting for review
   *   acr-2  approved   Bruno, reviewer agreed *and* rewrote the record
   *   acr-3  rejected   Carolina, reviewer disagreed, record left alone
   *   acr-4  withdrawn  Ana pulled her own request before anybody acted
   *
   * `acr-2` is the only one that touched its attendance row; that row carries
   * `status: "corrected"` and `corrections: 1` to match.
   */
  attendanceCorrectionRequests: [
    {
      id: "acr-1",
      attendanceId: "att-101",
      memberId: "stu-1001",
      kind: "missing-exit",
      reason: "The Lab 3 terminal did not read my card when I left at 12:15.",
      suggestedEntry: null,
      suggestedExit: "12:15",
      status: "pending",
      createdAt: "2026-08-26T18:05:00.000Z",
      resolvedAt: null,
      resolvedBy: null,
      resolutionNote: null,
      appliedToRecord: false,
    },
    {
      id: "acr-2",
      attendanceId: "att-91",
      memberId: "stu-1002",
      kind: "wrong-times",
      reason: "I stayed until about 17:50 to finish re-labelling the patch panel.",
      suggestedEntry: "14:00",
      suggestedExit: "17:50",
      status: "approved",
      createdAt: "2026-08-18T18:12:00.000Z",
      resolvedAt: "2026-08-18T18:40:00.000Z",
      resolvedBy: "System Administrator",
      resolutionNote: "Checked the Terminal B log — the exit scan failed. Corrected to 17:50.",
      appliedToRecord: true,
    },
    {
      id: "acr-3",
      attendanceId: "att-96",
      memberId: "stu-1003",
      kind: "wrong-day",
      reason: "I was at my own school that afternoon, not at the lab.",
      suggestedEntry: null,
      suggestedExit: null,
      status: "rejected",
      createdAt: "2026-08-21T19:02:00.000Z",
      resolvedAt: "2026-08-22T09:30:00.000Z",
      resolvedBy: "Paulo Rios",
      resolutionNote: "The gate camera and the card scan both place you in Lab 3 that afternoon. Record kept.",
      appliedToRecord: false,
    },
    {
      id: "acr-4",
      attendanceId: "att-85",
      memberId: "stu-1001",
      kind: "wrong-times",
      reason: "I thought my check-in was fifteen minutes early, but I misread it.",
      suggestedEntry: "08:15",
      suggestedExit: null,
      status: "withdrawn",
      createdAt: "2026-08-12T17:44:00.000Z",
      resolvedAt: "2026-08-12T17:58:00.000Z",
      resolvedBy: "Ana Beatriz Souza",
      resolutionNote: null,
      appliedToRecord: false,
    },
  ] as AttendanceCorrectionRequest[],
  devices: [
    {
      id: "dev-1",
      name: "Terminal A",
      location: "Main Gate",
      firmwareVersion: "1.4.2",
      firmwareChannel: "stable",
      status: "online",
      ipAddress: "192.168.10.21",
      wifiStrength: 89,
      lastHeartbeatAt: "2026-07-27T09:13:00.000Z",
      queueSize: 0,
      description: "Primary entrance attendance terminal.",
      heartbeatIntervalMinutes: 2,
      notes: "",
    },
    {
      id: "dev-2",
      name: "Terminal B",
      location: "Lab 3",
      firmwareVersion: "1.3.9",
      firmwareChannel: "beta",
      status: "warning",
      ipAddress: "192.168.10.34",
      wifiStrength: 56,
      lastHeartbeatAt: "2026-07-27T08:52:00.000Z",
      queueSize: 4,
      description: "Lab terminal with queued sync events.",
      heartbeatIntervalMinutes: 5,
      notes: "Investigate weak WiFi signal.",
    },
  ] as DeviceDetails[],
  /*
   * Only members who actually carry out an FCT internship appear here.
   *
   * `completedHours` and `remainingHours` are NOT stored. They used to be, in
   * four places at once, and a progress update wrote one of them — so the
   * internship page and the member page disagreed after the first edit. They are
   * now summed from the attendance that falls inside the member's internship
   * participation periods. `requiredHours` stays stored: it is a school rule, not
   * a sum of scans.
   *
   * `startDate` matches the member's internship participation period below. The
   * period is what classifies attendance; this date is the internship's own
   * record of when it began, and the two must agree.
   */
  internships: [
    {
      id: "int-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      hostEntity: "Escola Secundária Augusto Cabrita",
      requiredHours: 240,
      orientador: "Prof. L. Santos",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-07-15",
      endDate: "2026-11-30",
      status: "active",
      notes: "Weekly review every Friday. Volunteered with the team before the placement began.",
      certificateIssuedAt: null,
    },
    {
      id: "int-2",
      studentId: "stu-1003",
      studentName: "Carolina Mendes Rocha",
      hostEntity: "Escola Secundária Augusto Cabrita",
      requiredHours: 210,
      orientador: "Prof.ª C. Marques",
      monitor: "Eng. R. Ferreira",
      startDate: "2026-07-01",
      endDate: "2026-12-18",
      status: "active",
      notes: "Attendance sheet countersigned by Escola Secundária de Barreiro.",
      certificateIssuedAt: null,
    },
  ] as StoredInternship[],

  /*
   * How each member was participating, over time.
   *
   * Ana is the worked example: a volunteer through June and the first half of
   * July, an FCT intern from 15 July. Her June hours stay volunteer hours
   * forever — that is the whole point of storing periods instead of reading her
   * current status. Bruno never became an intern, so his single period is still
   * open. Carolina transitioned earlier, on 1 July, so the transition date is not
   * a constant anywhere in the code.
   *
   * Both ends are inclusive and whole-day: 14 July is entirely volunteer time and
   * 15 July is entirely internship time.
   */
  participationPeriods: [
    {
      id: "pp-1",
      memberId: "stu-1001",
      kind: "team-member",
      startDate: "2026-06-01",
      endDate: "2026-07-14",
      internshipId: null,
      note: "Volunteered with the team before the FCT placement was arranged.",
    },
    {
      id: "pp-2",
      memberId: "stu-1001",
      kind: "internship",
      startDate: "2026-07-15",
      endDate: "2026-11-30",
      internshipId: "int-1",
      note: "FCT placement began. Hours from here count towards the 240h requirement.",
    },
    {
      id: "pp-3",
      memberId: "stu-1002",
      kind: "team-member",
      startDate: "2026-06-01",
      endDate: null,
      internshipId: null,
      note: "Volunteer team member. No placement arranged.",
    },
    {
      id: "pp-4",
      memberId: "stu-1003",
      kind: "team-member",
      startDate: "2026-06-01",
      endDate: "2026-06-30",
      internshipId: null,
      note: "Volunteered while the placement paperwork was completed.",
    },
    {
      id: "pp-5",
      memberId: "stu-1003",
      kind: "internship",
      startDate: "2026-07-01",
      endDate: "2026-12-18",
      internshipId: "int-2",
      note: "FCT placement began.",
    },
  ] as ParticipationPeriod[],
  announcements: [
    {
      id: "ann-1",
      title: "Report submission window",
      body: "Monthly attendance reports are available until Friday. Generate yours from the Reports page before the deadline.",
      audience: "all",
      priority: "important",
      status: "published",
      publishedAt: "2026-07-27",
      createdAt: "2026-07-26T18:00:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
    {
      id: "ann-2",
      title: "Card replacement reminder",
      body: "Notify the support desk if your RFID card is lost so attendance is not interrupted.",
      audience: "all",
      priority: "normal",
      status: "published",
      publishedAt: "2026-07-24",
      createdAt: "2026-07-24T09:30:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
    {
      id: "ann-3",
      title: "Plano de trabalho individual due",
      body: "Official interns must hand the signed plano de trabalho individual to the professor orientador this week.",
      audience: "official-internship",
      priority: "urgent",
      status: "published",
      publishedAt: "2026-07-22",
      createdAt: "2026-07-22T08:15:00.000Z",
      createdBy: "Paulo Rios",
      updatedAt: null,
    },
    {
      id: "ann-4",
      title: "Surplus hours cut-off",
      body: "Hours registered after 31 July no longer count towards the current certificate period.",
      audience: "equipa-hours",
      priority: "important",
      status: "draft",
      publishedAt: null,
      createdAt: "2026-07-28T11:00:00.000Z",
      createdBy: "Carla Menezes",
      updatedAt: null,
    },
  ] as AnnouncementSummary[],
  /*
   * Five projects spanning every status the board can show: two active, one
   * paused, one still planned and one finished. Ids are unchanged from the
   * original fixture so existing `dailyLogs.projectId` values still resolve.
   */
  projects: [
    {
      id: "prj-terminals",
      name: "RFID attendance terminals",
      description: "Build, test and deploy the attendance terminals for the main gate and the labs. Covers enclosure assembly, firmware flashing and the on-site test pass.",
      status: "active",
      priority: "high",
      ownerId: "user-2",
      owner: "Paulo Rios",
      startDate: "2026-02-17",
      deadline: "2026-09-30",
      memberIds: ["stu-1001", "stu-1003", "user-2"],
      coordinatorIds: ["stu-1001"],
      createdAt: "2026-02-17T09:00:00.000Z",
      updatedAt: "2026-07-27T16:20:00.000Z",
      archivedAt: null,
    },
    {
      id: "prj-inventory",
      name: "Lab inventory and documentation",
      description: "Keep the hardware inventory and the wiring documentation current so the labs can be handed over at the end of the year.",
      status: "paused",
      priority: "low",
      ownerId: "user-1",
      owner: "Carla Menezes",
      startDate: "2026-03-02",
      deadline: null,
      memberIds: ["stu-1001"],
      coordinatorIds: [],
      createdAt: "2026-03-02T10:00:00.000Z",
      updatedAt: "2026-07-26T12:40:00.000Z",
      archivedAt: null,
    },
    {
      id: "prj-network",
      name: "Block B network refresh",
      description: "Switch replacement and structured cabling clean-up across block B, including patch panel labelling.",
      status: "active",
      priority: "normal",
      ownerId: "user-2",
      owner: "Paulo Rios",
      startDate: "2026-05-04",
      deadline: "2026-09-30",
      memberIds: ["stu-1002", "stu-1001"],
      coordinatorIds: [],
      createdAt: "2026-05-04T08:30:00.000Z",
      updatedAt: "2026-07-20T11:05:00.000Z",
      archivedAt: null,
    },
    {
      id: "prj-openday",
      name: "Open day demo stand",
      description: "Prepare the Equipa Tecnica stand for the school open day: demo hardware, posters and a rota of members to staff it.",
      status: "planned",
      priority: "normal",
      ownerId: "user-1",
      owner: "Carla Menezes",
      startDate: "2026-09-01",
      deadline: "2026-10-24",
      memberIds: ["stu-1002", "stu-1003"],
      coordinatorIds: ["stu-1002"],
      createdAt: "2026-07-15T14:00:00.000Z",
      updatedAt: null,
      archivedAt: null,
    },
    {
      id: "prj-printers",
      name: "Staff room printer migration",
      description: "Move the staff room printers onto the new print server and retire the direct-IP queues.",
      status: "done",
      priority: "normal",
      ownerId: "user-2",
      owner: "Paulo Rios",
      startDate: "2026-01-12",
      deadline: "2026-03-20",
      memberIds: ["stu-1002"],
      coordinatorIds: [],
      createdAt: "2026-01-12T09:15:00.000Z",
      updatedAt: "2026-03-18T16:00:00.000Z",
      archivedAt: null,
    },
  ] as Project[],

  /*
   * Work items across those projects, covering all five task states and both
   * assigned and unowned work. Two tasks are deliberately left with no assignee
   * so the unassigned queue has something in it.
   */
  projectTasks: [
    {
      id: "tsk-1",
      projectId: "prj-terminals",
      title: "Assemble the gate terminal enclosures",
      description: "Cut and drill the two gate enclosures, fit the reader board and route the antenna away from the case wall.",
      status: "done",
      priority: "high",
      assigneeIds: ["stu-1001"],
      dueDate: "2026-07-25",
      estimatedHours: 8,
      createdAt: "2026-07-14T09:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-07-27T12:35:00.000Z",
      completedAt: "2026-07-27T12:35:00.000Z",
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-2",
      projectId: "prj-terminals",
      title: "Flash firmware 1.4.2 onto the lab terminals",
      description: "Roll the stable channel build onto Terminal B and re-run the UID read tests afterwards.",
      status: "in-progress",
      priority: "high",
      assigneeIds: ["stu-1003"],
      dueDate: "2026-09-04",
      estimatedHours: 6,
      createdAt: "2026-07-20T10:30:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-07-27T16:20:00.000Z",
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-3",
      projectId: "prj-terminals",
      title: "Investigate Terminal B dropping off the network mid-flash",
      description: "The lab terminal loses its WiFi association during OTA. Check signal strength and the retry window in the firmware.",
      status: "blocked",
      priority: "critical",
      assigneeIds: ["stu-1003", "user-2"],
      dueDate: "2026-08-26",
      estimatedHours: 4,
      createdAt: "2026-07-24T15:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-07-26T09:10:00.000Z",
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-4",
      projectId: "prj-terminals",
      title: "Write the terminal acceptance checklist",
      description: "One page listing every check a terminal has to pass before it is mounted on a wall.",
      status: "review",
      priority: "normal",
      assigneeIds: ["stu-1003"],
      dueDate: "2026-09-11",
      estimatedHours: 3,
      createdAt: "2026-07-22T11:00:00.000Z",
      createdBy: "Carla Menezes",
      createdById: "user-1",
      updatedAt: "2026-07-24T15:45:00.000Z",
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-5",
      projectId: "prj-terminals",
      title: "Mount and commission the second gate terminal",
      description: "Fix the unit by the side entrance, run power, and register it in the devices page.",
      status: "todo",
      priority: "normal",
      assigneeIds: [],
      dueDate: "2026-09-25",
      estimatedHours: 5,
      createdAt: "2026-07-26T08:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: null,
      completedAt: null,
      archivedAt: null,
      order: 1,
    },
    {
      id: "tsk-6",
      projectId: "prj-network",
      title: "Label the block B patch panels",
      description: "Apply the school naming convention to every port and update the cabling plan to match.",
      status: "done",
      priority: "normal",
      assigneeIds: ["stu-1002"],
      dueDate: "2026-06-20",
      estimatedHours: 6,
      createdAt: "2026-06-08T09:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-06-18T16:10:00.000Z",
      completedAt: "2026-06-18T16:10:00.000Z",
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-7",
      projectId: "prj-network",
      title: "Swap the block B floor switch",
      description: "Replace the failing 24-port switch and move the uplinks over outside teaching hours.",
      status: "in-progress",
      priority: "high",
      assigneeIds: ["stu-1001", "user-2"],
      dueDate: "2026-08-28",
      estimatedHours: 10,
      createdAt: "2026-06-22T10:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-07-20T11:05:00.000Z",
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-8",
      projectId: "prj-network",
      title: "Re-test every block B room after the swap",
      description: "Confirm link and speed on one port per room and note anything that stays down.",
      status: "todo",
      priority: "normal",
      assigneeIds: ["stu-1002"],
      dueDate: "2026-09-05",
      estimatedHours: 4,
      createdAt: "2026-06-22T10:05:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: null,
      completedAt: null,
      archivedAt: null,
      order: 1,
    },
    {
      id: "tsk-9",
      projectId: "prj-inventory",
      title: "Photograph and tag the lab 3 hardware",
      description: "Every machine gets an asset tag, a photo and a row in the inventory sheet.",
      status: "in-progress",
      priority: "low",
      assigneeIds: ["stu-1001"],
      dueDate: "2026-10-12",
      estimatedHours: 12,
      createdAt: "2026-07-01T09:30:00.000Z",
      createdBy: "Carla Menezes",
      createdById: "user-1",
      updatedAt: "2026-07-26T12:40:00.000Z",
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-10",
      projectId: "prj-inventory",
      title: "Redraw the attendance terminal wiring diagram",
      description: "The current diagram predates the reader change. Redraw it from the assembled units.",
      status: "todo",
      priority: "low",
      assigneeIds: [],
      dueDate: null,
      estimatedHours: 3,
      createdAt: "2026-07-05T14:00:00.000Z",
      createdBy: "Carla Menezes",
      createdById: "user-1",
      updatedAt: null,
      completedAt: null,
      archivedAt: null,
      order: 1,
    },
    {
      id: "tsk-11",
      projectId: "prj-openday",
      title: "Draft the stand layout and demo list",
      description: "Decide which projects are demonstrated and how the table is arranged.",
      status: "todo",
      priority: "normal",
      assigneeIds: ["stu-1003"],
      dueDate: "2026-09-19",
      estimatedHours: 4,
      createdAt: "2026-07-15T14:10:00.000Z",
      createdBy: "Carla Menezes",
      createdById: "user-1",
      updatedAt: null,
      completedAt: null,
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-12",
      projectId: "prj-openday",
      title: "Build the member rota for the day",
      description: "Two members per two-hour slot, covering the whole open day.",
      status: "todo",
      priority: "low",
      assigneeIds: ["stu-1002"],
      dueDate: "2026-10-10",
      estimatedHours: 2,
      createdAt: "2026-07-15T14:15:00.000Z",
      createdBy: "Carla Menezes",
      createdById: "user-1",
      updatedAt: null,
      completedAt: null,
      archivedAt: null,
      order: 1,
    },
    {
      id: "tsk-13",
      projectId: "prj-printers",
      title: "Point every staff room queue at the print server",
      description: "Remove the direct-IP queues and deploy the server queue to the staff room machines.",
      status: "done",
      priority: "normal",
      assigneeIds: ["stu-1002"],
      dueDate: "2026-03-14",
      estimatedHours: 6,
      createdAt: "2026-01-20T09:00:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-03-12T15:20:00.000Z",
      completedAt: "2026-03-12T15:20:00.000Z",
      archivedAt: null,
      order: 0,
    },
    {
      id: "tsk-14",
      projectId: "prj-printers",
      title: "Retire the old print queues",
      description: "Delete the unused direct-IP queues once a full week has passed with no fallback use.",
      status: "done",
      priority: "low",
      assigneeIds: ["stu-1002"],
      dueDate: "2026-03-20",
      estimatedHours: 1,
      createdAt: "2026-01-20T09:05:00.000Z",
      createdBy: "Paulo Rios",
      createdById: "user-2",
      updatedAt: "2026-03-18T16:00:00.000Z",
      completedAt: "2026-03-18T16:00:00.000Z",
      archivedAt: null,
      order: 1,
    },
  ] as ProjectTask[],

  /** The project audit trail. Appended to by the projects service. */
  projectActivity: [
    {
      id: "pac-1",
      projectId: "prj-terminals",
      taskId: "tsk-1",
      kind: "task-status-changed",
      summary: "Moved \"Assemble the gate terminal enclosures\" to Done",
      messageKey: "projects.activity.taskStatusChanged",
      messageParams: { title: "Assemble the gate terminal enclosures", status: "done" },
      actorId: "stu-1001",
      actorName: "Ana Beatriz Souza",
      createdAt: "2026-07-27T12:35:00.000Z",
    },
    {
      id: "pac-2",
      projectId: "prj-terminals",
      taskId: "tsk-2",
      kind: "task-updated",
      summary: "Updated \"Flash firmware 1.4.2 onto the lab terminals\"",
      messageKey: "projects.activity.taskUpdated",
      messageParams: { title: "Flash firmware 1.4.2 onto the lab terminals" },
      actorId: "stu-1003",
      actorName: "Carolina Mendes Rocha",
      createdAt: "2026-07-27T16:20:00.000Z",
    },
    {
      id: "pac-3",
      projectId: "prj-terminals",
      taskId: "tsk-3",
      kind: "task-status-changed",
      summary: "Moved \"Investigate Terminal B dropping off the network mid-flash\" to Blocked",
      messageKey: "projects.activity.taskStatusChanged",
      messageParams: { title: "Investigate Terminal B dropping off the network mid-flash", status: "blocked" },
      actorId: "user-2",
      actorName: "Paulo Rios",
      createdAt: "2026-07-26T09:10:00.000Z",
    },
    {
      id: "pac-4",
      projectId: "prj-inventory",
      taskId: "tsk-9",
      kind: "task-updated",
      summary: "Updated \"Photograph and tag the lab 3 hardware\"",
      messageKey: "projects.activity.taskUpdated",
      messageParams: { title: "Photograph and tag the lab 3 hardware" },
      actorId: "stu-1001",
      actorName: "Ana Beatriz Souza",
      createdAt: "2026-07-26T12:40:00.000Z",
    },
    {
      id: "pac-5",
      projectId: "prj-network",
      taskId: "tsk-7",
      kind: "task-assigned",
      summary: "Assigned \"Swap the block B floor switch\" to Ana Beatriz Souza, Paulo Rios",
      messageKey: "projects.activity.taskAssigned",
      messageParams: { title: "Swap the block B floor switch", names: "Ana Beatriz Souza, Paulo Rios" },
      actorId: "user-2",
      actorName: "Paulo Rios",
      createdAt: "2026-07-20T11:05:00.000Z",
    },
    {
      id: "pac-6",
      projectId: "prj-openday",
      taskId: null,
      kind: "project-created",
      summary: "Created the project",
      messageKey: "projects.activity.projectCreated",
      messageParams: {},
      actorId: "user-1",
      actorName: "Carla Menezes",
      createdAt: "2026-07-15T14:00:00.000Z",
    },
    {
      id: "pac-7",
      projectId: "prj-printers",
      taskId: "tsk-14",
      kind: "task-status-changed",
      summary: "Moved \"Retire the old print queues\" to Done",
      messageKey: "projects.activity.taskStatusChanged",
      messageParams: { title: "Retire the old print queues", status: "done" },
      actorId: "stu-1002",
      actorName: "Bruno Henrique Costa",
      createdAt: "2026-03-18T16:00:00.000Z",
    },
  ] as ProjectActivityEvent[],

  /*
   * Moments start empty on purpose: they expire 24 hours after posting, so a
   * seeded one would be gone by tomorrow and the gallery would look broken.
   * Post one from the student workspace to exercise the feature.
   */
  teamMoments: [] as TeamMoment[],
  dailyLogs: [
    {
      id: "log-d-1",
      studentId: "stu-1001",
      date: "2026-07-27",
      hours: 4.2,
      projectId: "prj-terminals",
      activities: "Assembled and tested two RFID terminals for the main gate.",
      learnings: "Learned how the RDM6300 reader reports UIDs over UART.",
      difficulties: "Intermittent readings when the antenna was too close to the case.",
      status: "submitted",
      createdAt: "2026-07-27T12:30:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-2",
      studentId: "stu-1001",
      date: "2026-07-26",
      hours: 4.1,
      projectId: "prj-inventory",
      activities: "Documented the attendance terminal wiring and updated the lab inventory.",
      learnings: "Improved technical writing for hardware documentation.",
      difficulties: "",
      status: "submitted",
      createdAt: "2026-07-26T12:20:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-3",
      studentId: "stu-1001",
      date: "2026-06-30",
      hours: 5,
      projectId: "prj-network",
      activities: "Supported the network team during the switch replacement in block B.",
      learnings: "First contact with structured cabling and patch panel labelling.",
      difficulties: "Cable labelling was inconsistent with the existing plan.",
      status: "submitted",
      createdAt: "2026-06-30T17:00:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-4",
      studentId: "stu-1003",
      date: "2026-07-27",
      hours: 4,
      projectId: "prj-terminals",
      activities: "Flashed the new firmware onto three terminals and re-ran the UID read tests.",
      learnings: "Understood how the OTA channel picks up a firmware build.",
      difficulties: "One terminal kept dropping off the network mid-flash.",
      status: "submitted",
      createdAt: "2026-07-27T16:10:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-5",
      studentId: "stu-1003",
      date: "2026-07-24",
      hours: 3.5,
      projectId: "prj-terminals",
      activities: "Wrote the terminal test checklist and ran it against the gate unit.",
      learnings: "Writing a checklist first made the retest much faster.",
      difficulties: "",
      status: "draft",
      createdAt: "2026-07-24T15:40:00.000Z",
      updatedAt: null,
    },
    {
      id: "log-d-6",
      studentId: "stu-1002",
      date: "2026-06-18",
      hours: 3,
      projectId: "prj-network",
      activities: "Helped label patch panels in block B and updated the cabling plan.",
      learnings: "Learned the school's patch panel naming convention.",
      difficulties: "",
      status: "submitted",
      createdAt: "2026-06-18T16:00:00.000Z",
      updatedAt: null,
    },
  ] as DailyLogEntry[],
  monthlyReports: [
    {
      id: "mr-1",
      studentId: "stu-1001",
      month: "2026-06",
      periodStart: "2026-06-01",
      periodEnd: "2026-06-30",
      totalHours: 5,
      entriesCount: 1,
      activitiesCompleted: ["Supported the network team during the switch replacement in block B."],
      activitiesPlanned: ["Finish the terminal enclosure assembly.", "Start the internship dossier."],
      mainDifficulties: "Cable labelling was inconsistent with the existing plan.",
      status: "submitted",
      generatedAt: "2026-07-01T09:00:00.000Z",
      submittedAt: "2026-07-01T10:15:00.000Z",
      reviewedAt: null,
      reviewedBy: null,
      reviewNote: "",
    },
    /*
     * A draft, so the history list has something the student can still open and
     * finish. Draft monthly reports were unreachable once created — the table
     * offered only "Submit" — which is what made "Draft" a label rather than a state.
     */
    {
      id: "mr-2",
      studentId: "stu-1001",
      month: "2026-07",
      periodStart: "2026-07-01",
      periodEnd: "2026-07-31",
      totalHours: 6,
      entriesCount: 2,
      activitiesCompleted: [
        "Assembled two terminal enclosures and fitted the readers.",
        "Traced the intermittent fault on the Lab 3 terminal to a loose ribbon cable.",
      ],
      activitiesPlanned: ["Finish the terminal enclosure assembly.", "Start the internship dossier."],
      mainDifficulties: "The replacement ribbon cables did not arrive until the end of the month.",
      status: "draft",
      generatedAt: "2026-08-02T08:40:00.000Z",
      submittedAt: null,
      reviewedAt: null,
      reviewedBy: null,
      reviewNote: "",
    },
  ] as MonthlyReport[],
  finalReports: {
    "stu-1001": {
      studentId: "stu-1001",
      periodStart: "2026-07-15",
      periodEnd: "2026-11-30",
      companyCharacterization: "",
      activitiesPerformed: "",
      difficulties: "",
      newLearnings: "",
      occurrences: "",
      other: "",
      status: "draft",
      updatedAt: null,
      submittedAt: null,
      reviewedAt: null,
      reviewedBy: null,
      reviewNote: "",
    },
  } as Record<string, FinalReport>,
  users: [
    {
      id: "user-1",
      fullName: "Carla Menezes",
      email: "carla.menezes@picaponto.edu",
      role: "administrator",
      status: "active",
      lastLoginAt: "2026-07-27T08:05:00.000Z",
      memberId: null,
      permissions: null,
    },
    {
      id: "user-2",
      fullName: "Paulo Rios",
      email: "paulo.rios@picaponto.edu",
      role: "coordinator",
      status: "active",
      lastLoginAt: "2026-07-26T19:40:00.000Z",
      memberId: null,
      // An explicit grant on top of the coordinator preset, so the override path
      // has something real behind it rather than only ever being null.
      permissions: ["users:update", "users:reset-password", "members:grant-access", "users:create"],
    },
    {
      // Created from a member record, so the roster shows this member as having access.
      id: "user-3",
      fullName: "Ana Beatriz Souza",
      email: "ana.souza@picaponto.edu",
      role: "viewer",
      status: "active",
      lastLoginAt: "2026-07-25T09:12:00.000Z",
      memberId: "stu-1001",
      permissions: null,
    },
  ] as UserSummary[],
  /*
   * Which member has opened which announcement.
   *
   * Seeded with the two oldest notices already read by the student account, so
   * the page opens with a believable mix rather than everything unread.
   */
  announcementReads: [
    { memberId: "stu-1001", announcementId: "ann-2", readAt: "2026-07-24T18:20:00.000Z" },
    { memberId: "stu-1001", announcementId: "ann-3", readAt: "2026-07-23T08:05:00.000Z" },
  ] as AnnouncementRead[],

  /*
   * Newest first, the order `appendAuditLog` maintains by unshifting.
   *
   * The `attendance-correction` entries are the trail the four seeded requests
   * in `attendanceCorrectionRequests` necessarily left behind: a CREATE when the
   * member raised it, and an UPDATE when it reached a terminal state. They are
   * written in the exact shape the correction service produces, so a request
   * resolved in the running app is indistinguishable from these. `acr-1` is
   * still pending and so has a CREATE and nothing else.
   */
  auditLogs: [
    {
      id: "log-3",
      timestamp: "2026-08-26T18:05:00.000Z",
      userName: "Ana Beatriz Souza",
      action: "CREATE",
      entity: "attendance-correction",
      description: "Correction requested for 2026-08-26: The Lab 3 terminal did not read my card when I left at 12:15.",
      ipAddress: "—",
      deviceName: "Student portal",
    },
    {
      id: "log-4",
      timestamp: "2026-08-22T09:30:00.000Z",
      userName: "Paulo Rios",
      action: "UPDATE",
      entity: "attendance-correction",
      description: "Rejected Carolina Mendes Rocha's request without changing the record.",
      ipAddress: "—",
      deviceName: "Admin Console",
    },
    {
      id: "log-5",
      timestamp: "2026-08-21T19:02:00.000Z",
      userName: "Carolina Mendes Rocha",
      action: "CREATE",
      entity: "attendance-correction",
      description: "Correction requested for 2026-08-21: I was at my own school that afternoon, not at the lab.",
      ipAddress: "—",
      deviceName: "Student portal",
    },
    {
      id: "log-6",
      timestamp: "2026-08-18T18:40:00.000Z",
      userName: "System Administrator",
      action: "UPDATE",
      entity: "attendance-correction",
      description: "Approved Bruno Henrique Costa's request and corrected the 2026-08-18 record.",
      ipAddress: "—",
      deviceName: "Admin Console",
    },
    {
      id: "log-7",
      timestamp: "2026-08-18T18:12:00.000Z",
      userName: "Bruno Henrique Costa",
      action: "CREATE",
      entity: "attendance-correction",
      description: "Correction requested for 2026-08-18: I stayed until about 17:50 to finish re-labelling the patch panel.",
      ipAddress: "—",
      deviceName: "Student portal",
    },
    {
      id: "log-8",
      timestamp: "2026-08-12T17:58:00.000Z",
      userName: "Ana Beatriz Souza",
      action: "UPDATE",
      entity: "attendance-correction",
      description: "Withdrew their own correction request.",
      ipAddress: "—",
      deviceName: "Student portal",
    },
    {
      id: "log-9",
      timestamp: "2026-08-12T17:44:00.000Z",
      userName: "Ana Beatriz Souza",
      action: "CREATE",
      entity: "attendance-correction",
      description: "Correction requested for 2026-08-12: I thought my check-in was fifteen minutes early, but I misread it.",
      ipAddress: "—",
      deviceName: "Student portal",
    },
    {
      id: "log-1",
      timestamp: "2026-07-27T09:02:00.000Z",
      userName: "Carla Menezes",
      action: "CREATE",
      entity: "attendance",
      description: "Manual correction created for Bruno Henrique Costa.",
      ipAddress: "192.168.10.12",
      deviceName: "Admin Console",
    },
    {
      id: "log-2",
      timestamp: "2026-07-27T08:59:00.000Z",
      userName: "System",
      action: "UPDATE",
      entity: "device",
      description: "Heartbeat updated for Terminal A.",
      ipAddress: "192.168.10.21",
      deviceName: "Terminal A",
    },
  ] as AuditLogEntry[],
  settings: {
    schoolName: "Pica Ponto Institute",
    logoUrl: "",
    theme: "light",
    language: "Portuguese (Brazil)",
    timezone: "America/Sao_Paulo",
    attendance: {
      duplicateScanTimeoutMinutes: 15,
      workingDayStart: "07:00",
      workingDayEnd: "18:00",
      entryToleranceMinutes: 10,
      exitToleranceMinutes: 10,
    },
    devices: {
      otaEnabled: true,
      apiUrl: "https://api.picaponto.local",
      backupEnabled: true,
      backupPath: "C:/PicaPonto/backups",
    },
    security: {
      confirmNewDevices: true,
      sessionTimeoutMinutes: 60,
      twoFactorEnabled: false,
      trustedDevices: [
        { id: "dev-1", name: "Lab desktop — Windows", lastUsedAt: "2026-07-27T08:02:00.000Z", current: true },
        { id: "dev-2", name: "Coordination laptop — Windows", lastUsedAt: "2026-07-24T17:41:00.000Z", current: false },
      ],
    },
    workHours: {
      schedule: [
        { weekday: "monday", open: true, start: "08:30", end: "17:30" },
        { weekday: "tuesday", open: true, start: "08:30", end: "17:30" },
        { weekday: "wednesday", open: true, start: "08:30", end: "17:30" },
        { weekday: "thursday", open: true, start: "08:30", end: "17:30" },
        { weekday: "friday", open: true, start: "08:30", end: "16:00" },
        { weekday: "saturday", open: false, start: "09:00", end: "13:00" },
        { weekday: "sunday", open: false, start: "09:00", end: "13:00" },
      ],
      expectedWeeklyHours: 20,
      closedDates: ["2026-12-24", "2026-12-25", "2026-12-31"],
    },
    logRetentionDays: 365,
  } as ApplicationSettings,
  portal: {
    profile: {
      fullName: "Ana Beatriz Souza",
      studentNumber: "2023001",
      course: "Information Systems",
      className: "IS-3A",
      photoUrl: null,
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      assignedOrientador: "Prof. L. Santos",
      assignedMonitor: "Eng. R. Ferreira",
    },
    attendanceToday: "present",
    /*
     * `attendanceCalendar` was here: seven fixed July dates with `absent` and
     * `holiday` statuses that are not in `AttendanceStatus`. It was a third copy
     * of days the `attendance` collection already holds, so the dashboard, the
     * calendar and the attendance page could disagree about the same day and a
     * correction never reached two of them. Both surfaces now project
     * `attendance`, scoped to the session's member.
     */
    /*
     * `recentAttendance`, `weeklyStatistics` and `monthlyStatistics` were here,
     * alongside the `attendanceCalendar` removed above, and had the same defect:
     * they were hand-written and owed nothing to the `attendance` collection.
     * The rhythm bars credited this member 6h every Tuesday and Friday when her
     * rota is Monday/Wednesday/Thursday, and `recentAttendance` listed three
     * July days that no record backs — under a heading claiming they were the
     * days behind her hour totals.
     *
     * All three are now derived from `attendance` by `src/utils/attendanceStats.ts`,
     * so an approved correction moves the charts and the tables together.
     */
    /*
     * `currentInternshipStatus`, `completedHours`, `remainingHours` and
     * `internshipProgress` were here — a fourth copy of the internship's hours.
     * The portal service now derives all four from the member's internship record
     * and their internship participation hours, so the student dashboard cannot
     * show a different number from the admin internship page.
     */
    achievements: [
      {
        id: "ach-1",
        title: "Perfect week",
        description: "Completed five consecutive days with on-time scans.",
        achievedAt: "2026-07-20",
      },
      {
        id: "ach-2",
        title: "Internship milestone",
        description: "Reached 50% of required internship hours.",
        achievedAt: "2026-07-18",
      },
    ],
    announcements: [
      {
        id: "ann-1",
        title: "Report submission window",
        description: "Monthly attendance reports are available until Friday.",
        publishedAt: "2026-07-27",
      },
      {
        id: "ann-2",
        title: "Card replacement reminder",
        description: "Notify the support desk if your RFID card is lost.",
        publishedAt: "2026-07-24",
      },
    ],
  } as StoredPortalSummary,
  memberHistory: {
    "stu-1001": [
      { id: "hist-1", date: "2026-07-27", entry: "07:58", exit: "12:10", hours: 4.2, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-2", date: "2026-07-26", entry: "07:54", exit: "12:02", hours: 4.1, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-3", date: "2026-07-25", entry: "—", exit: "—", hours: 0, deviceName: "—", status: "missing" },
    ] as MemberAttendanceHistoryItem[],
    "stu-1002": [
      { id: "hist-4", date: "2026-07-27", entry: "—", exit: "—", hours: 0, deviceName: "Terminal B - Lab", status: "missing" },
      { id: "hist-5", date: "2026-07-26", entry: "08:10", exit: "12:17", hours: 4.1, deviceName: "Terminal B - Lab", status: "corrected" },
    ] as MemberAttendanceHistoryItem[],
  } as Record<string, MemberAttendanceHistoryItem[]>,
  /*
   * `memberInternships` was here: a third copy of each internship, keyed by member.
   * It held its own `completedHours`/`remainingHours`, which `updateInternshipProgress`
   * never wrote, so it drifted from the internship record on the first edit.
   * `getMemberInternship` now projects the internship record and derives the hours.
   */
};
