import type { ApplicationSettings } from "../types/settings";
import type { AuditLogEntry } from "../types/audit";
import type { AttendanceSummary } from "../types/attendance";
import type { DeviceDetails } from "../types/devices";
import type { InternshipSummary } from "../types/internships";
import type { RfidCardSummary } from "../types/cards";
import type { MemberAttendanceHistoryItem, MemberDetails, MemberInternshipSummary } from "../types/members";
import type { StudentPortalSummary } from "../types/portal";
import type { UserSummary } from "../types/users";

export const mockDatabase = {
  members: [
    {
      id: "stu-1001",
      photoUrl: null,
      memberNumber: "2023001",
      fullName: "Ana Beatriz Souza",
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      course: "Information Systems",
      className: "IS-3A",
      academicYear: "2026",
      status: "active",
      assignedCardUid: "04A1C3E9",
      internshipStatus: "in-progress",
      accumulatedHours: 128,
      birthDate: "2004-03-12",
      emergencyContact: "Marcos Souza - +55 11 97777-1122",
      notes: "Prefers afternoon attendance reports.",
      supervisorName: "Prof. L. Santos",
      internshipRequiredHours: 240,
      internshipCompletedHours: 128,
      internshipStartDate: "2026-02-10",
      internshipEndDate: "2026-11-30",
    },
    {
      id: "stu-1002",
      photoUrl: null,
      memberNumber: "2023002",
      fullName: "Bruno Henrique Costa",
      email: "bruno.costa@picaponto.edu",
      phone: "+55 11 98888-1002",
      course: "Computer Engineering",
      className: "CE-2B",
      academicYear: "2026",
      status: "active",
      assignedCardUid: null,
      internshipStatus: "not-assigned",
      accumulatedHours: 92,
      birthDate: "2003-10-21",
      emergencyContact: "Fernanda Costa - +55 11 97777-2233",
      notes: "Requires card assignment.",
      supervisorName: null,
      internshipRequiredHours: 220,
      internshipCompletedHours: 0,
      internshipStartDate: null,
      internshipEndDate: null,
    },
  ] as MemberDetails[],
  cards: [
    {
      id: "card-1",
      uid: "04A1C3E9",
      ownerName: "Ana Beatriz Souza",
      ownerId: "stu-1001",
      status: "assigned",
      lastScanAt: "2026-07-27T08:54:00.000Z",
      assignedAt: "2026-02-01T08:00:00.000Z",
      replacedByUid: null,
    },
    {
      id: "card-2",
      uid: "09F7B1D2",
      ownerName: null,
      ownerId: null,
      status: "available",
      lastScanAt: null,
      assignedAt: null,
      replacedByUid: null,
    },
  ] as RfidCardSummary[],
  attendance: [
    {
      id: "att-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      course: "Information Systems",
      className: "IS-3A",
      date: "2026-07-27",
      entry: "07:58",
      exit: "12:10",
      hours: 4.2,
      deviceName: "Terminal A - Main Gate",
      deviceId: "dev-1",
      status: "present",
      corrections: 0,
      notes: "",
      createdBy: "System",
      updatedBy: null,
      updatedAt: null,
    },
    {
      id: "att-2",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      course: "Computer Engineering",
      className: "CE-2B",
      date: "2026-07-27",
      entry: null,
      exit: null,
      hours: null,
      deviceName: "Terminal B - Lab",
      deviceId: "dev-2",
      status: "missing",
      corrections: 1,
      notes: "Manual correction requested.",
      createdBy: "Admin",
      updatedBy: "Coordinator",
      updatedAt: "2026-07-27T09:15:00.000Z",
    },
  ] as AttendanceSummary[],
  devices: [
    {
      id: "dev-1",
      name: "Terminal A",
      location: "Main Gate",
      firmwareVersion: "1.4.2",
      firmwareChannel: "stable",
      status: "online",
      ipAddress: "192.168.10.21",
      wifiStrength: 89,
      lastHeartbeatAt: "2026-07-27T09:13:00.000Z",
      queueSize: 0,
      description: "Primary entrance attendance terminal.",
      heartbeatIntervalMinutes: 2,
      notes: "",
    },
    {
      id: "dev-2",
      name: "Terminal B",
      location: "Lab 3",
      firmwareVersion: "1.3.9",
      firmwareChannel: "beta",
      status: "warning",
      ipAddress: "192.168.10.34",
      wifiStrength: 56,
      lastHeartbeatAt: "2026-07-27T08:52:00.000Z",
      queueSize: 4,
      description: "Lab terminal with queued sync events.",
      heartbeatIntervalMinutes: 5,
      notes: "Investigate weak WiFi signal.",
    },
  ] as DeviceDetails[],
  internships: [
    {
      id: "int-1",
      studentId: "stu-1001",
      studentName: "Ana Beatriz Souza",
      requiredHours: 240,
      completedHours: 128,
      remainingHours: 112,
      supervisor: "Prof. L. Santos",
      startDate: "2026-02-10",
      endDate: "2026-11-30",
      status: "active",
      notes: "Weekly review every Friday.",
      certificateIssuedAt: null,
    },
    {
      id: "int-2",
      studentId: "stu-1002",
      studentName: "Bruno Henrique Costa",
      requiredHours: 220,
      completedHours: 92,
      remainingHours: 128,
      supervisor: "Prof. M. Lima",
      startDate: "2026-03-01",
      endDate: "2026-12-15",
      status: "planned",
      notes: "Waiting on company assignment.",
      certificateIssuedAt: null,
    },
  ] as InternshipSummary[],
  users: [
    {
      id: "user-1",
      fullName: "Carla Menezes",
      email: "carla.menezes@picaponto.edu",
      role: "administrator",
      status: "active",
      lastLoginAt: "2026-07-27T08:05:00.000Z",
    },
    {
      id: "user-2",
      fullName: "Paulo Rios",
      email: "paulo.rios@picaponto.edu",
      role: "coordinator",
      status: "active",
      lastLoginAt: "2026-07-26T19:40:00.000Z",
    },
  ] as UserSummary[],
  auditLogs: [
    {
      id: "log-1",
      timestamp: "2026-07-27T09:02:00.000Z",
      userName: "Carla Menezes",
      action: "CREATE",
      entity: "attendance",
      description: "Manual correction created for Bruno Henrique Costa.",
      ipAddress: "192.168.10.12",
      deviceName: "Admin Console",
    },
    {
      id: "log-2",
      timestamp: "2026-07-27T08:59:00.000Z",
      userName: "System",
      action: "UPDATE",
      entity: "device",
      description: "Heartbeat updated for Terminal A.",
      ipAddress: "192.168.10.21",
      deviceName: "Terminal A",
    },
  ] as AuditLogEntry[],
  settings: {
    schoolName: "Pica Ponto Institute",
    logoUrl: "",
    theme: "dark",
    language: "Portuguese (Brazil)",
    timezone: "America/Sao_Paulo",
    attendance: {
      duplicateScanTimeoutMinutes: 15,
      workingDayStart: "07:00",
      workingDayEnd: "18:00",
      entryToleranceMinutes: 10,
      exitToleranceMinutes: 10,
    },
    devices: {
      otaEnabled: true,
      apiUrl: "https://api.picaponto.local",
      backupEnabled: true,
      backupPath: "C:/PicaPonto/backups",
    },
    notifications: {
      emailEnabled: true,
      desktopEnabled: true,
      recipients: "support@picaponto.edu",
    },
    logRetentionDays: 365,
  } as ApplicationSettings,
  portal: {
    profile: {
      fullName: "Ana Beatriz Souza",
      studentNumber: "2023001",
      course: "Information Systems",
      className: "IS-3A",
      photoUrl: null,
      email: "ana.souza@picaponto.edu",
      phone: "+55 11 98888-1001",
      assignedSupervisor: "Prof. L. Santos",
    },
    currentInternshipStatus: "In progress",
    completedHours: 128,
    remainingHours: 112,
    attendanceToday: "Present",
    attendanceCalendar: [
      { date: "2026-07-21", status: "present" },
      { date: "2026-07-22", status: "present" },
      { date: "2026-07-23", status: "late" },
      { date: "2026-07-24", status: "present" },
      { date: "2026-07-25", status: "holiday" },
      { date: "2026-07-26", status: "absent" },
      { date: "2026-07-27", status: "present" },
    ],
    recentAttendance: [
      { date: "2026-07-27", entry: "07:58", exit: "12:10", hours: 4.2, status: "Present" },
      { date: "2026-07-26", entry: "07:54", exit: "12:02", hours: 4.1, status: "Present" },
      { date: "2026-07-25", entry: "—", exit: "—", hours: 0, status: "Holiday" },
    ],
    weeklyStatistics: [
      { label: "Mon", value: 6 },
      { label: "Tue", value: 7 },
      { label: "Wed", value: 8 },
      { label: "Thu", value: 7 },
      { label: "Fri", value: 6 },
      { label: "Sat", value: 0 },
      { label: "Sun", value: 0 },
    ],
    monthlyStatistics: [
      { label: "Week 1", value: 34 },
      { label: "Week 2", value: 37 },
      { label: "Week 3", value: 33 },
      { label: "Week 4", value: 40 },
    ],
    internshipProgress: 53,
    achievements: [
      {
        id: "ach-1",
        title: "Perfect week",
        description: "Completed five consecutive days with on-time scans.",
        achievedAt: "2026-07-20",
      },
      {
        id: "ach-2",
        title: "Internship milestone",
        description: "Reached 50% of required internship hours.",
        achievedAt: "2026-07-18",
      },
    ],
    announcements: [
      {
        id: "ann-1",
        title: "Report submission window",
        description: "Monthly attendance reports are available until Friday.",
        publishedAt: "2026-07-27",
      },
      {
        id: "ann-2",
        title: "Card replacement reminder",
        description: "Notify the support desk if your RFID card is lost.",
        publishedAt: "2026-07-24",
      },
    ],
  } as StudentPortalSummary,
  memberHistory: {
    "stu-1001": [
      { id: "hist-1", date: "2026-07-27", entry: "07:58", exit: "12:10", hours: 4.2, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-2", date: "2026-07-26", entry: "07:54", exit: "12:02", hours: 4.1, deviceName: "Terminal A - Main Gate", status: "present" },
      { id: "hist-3", date: "2026-07-25", entry: "—", exit: "—", hours: 0, deviceName: "—", status: "missing" },
    ] as MemberAttendanceHistoryItem[],
    "stu-1002": [
      { id: "hist-4", date: "2026-07-27", entry: "—", exit: "—", hours: 0, deviceName: "Terminal B - Lab", status: "missing" },
      { id: "hist-5", date: "2026-07-26", entry: "08:10", exit: "12:17", hours: 4.1, deviceName: "Terminal B - Lab", status: "corrected" },
    ] as MemberAttendanceHistoryItem[],
  } as Record<string, MemberAttendanceHistoryItem[]>,
  memberInternships: {
    "stu-1001": {
      memberId: "stu-1001",
      requiredHours: 240,
      completedHours: 128,
      remainingHours: 112,
      supervisor: "Prof. L. Santos",
      startDate: "2026-02-10",
      endDate: "2026-11-30",
      status: "in-progress",
    } as MemberInternshipSummary,
    "stu-1002": {
      memberId: "stu-1002",
      requiredHours: 220,
      completedHours: 92,
      remainingHours: 128,
      supervisor: "Prof. M. Lima",
      startDate: "2026-03-01",
      endDate: "2026-12-15",
      status: "not-assigned",
    } as MemberInternshipSummary,
  } as Record<string, MemberInternshipSummary>,
};
